### ISSUE TITLE
LinkedIn Configuration

### ISSUE THREAD

**Issue by cwhiteley** [fastify/fastify-oauth2#1]
oauthPlugin.LINKEDIN_CONFIGURATION = {
    authorizeHost: 'https://www.linkedin.com',
    authorizePath: '/oauth/v2/authorization',
    tokenHost: 'https://www.linkedin.com',
    tokenPath: '/oauth/v2/accessToken'
}

Noticed that you added another configuration type

**Comment by allevo** [comment]
Hi! 
Would you mind sending a PR?
