### ISSUE TITLE
[Apple Auth] Redirect by Authorization URL fails without a required query param "response_mode: 'form_post'"

### ISSUE THREAD

**Issue by avmaxim** [fastify/fastify-oauth2#116]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.3

### Plugin version

3.0.0

### Node.js version

12.19.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

A redirect to a generated apple's authorization URL fails with a message `invalid_request. response_mode must be form_post when name or email scope is requested` when a query parameter called `response_mode: 'form_post'` is not used in conjunction with another query parameter called `scope` with a value of either `name`, or `email`. See error message below

![image](https://user-images.githubusercontent.com/9191544/137312332-83ae3517-3741-49d8-8377-5617cead3341.png)

### Steps to Reproduce

1. Define `scope` as `['name email']` in Apple Fastify OAuth2 config.
2. Setup all other required configurations for Fastify OAuth2 library. See example below:
```
export const appleOAuth2Options: FastifyOAuth2Options = {
   name: 'appleOAuth2',
   scope: ['email name'],
   credentials: {
      client: {
        id: APPLE_CLIENT_ID,
        secret: APPLE_SECRET,
      },
      auth: oauthPlugin.APPLE_CONFIGURATION,
   },
   startRedirectPath: '<START_REDIRECT_PATH>',
   callbackUri: `<CALLBACK_URL>`,
};
```
3. Wire configuration from Step 2 with your backend application
4. Open a browser and specify a `startRedirectPath` so that Fastify can track this endpoint, generate Authorization URL for Apple and redirect you by this URL in the browser.

**Actual behavior:** Error message `invalid_request. response_mode must be form_post when name or email scope is requested` appears and authorization fails 

### Expected Behavior

Apple specs requires to specify an obligated query parameter called `response_mode: 'form_post'`. See this link for reference. Thus you have to modify a ``

Your current implementation looks like this (see [code for reference](https://github.com/fastify/fastify-oauth2/blob/986534505d6a4243b216e7a7b5b9261c297f5a90/index.js#L66)):
![image](https://user-images.githubusercontent.com/9191544/137311185-5d67e247-0491-426c-a38e-93942517d0d4.png).

It has to be rewritten like this:
```
function generateAuthorizationUri (requestObject) {
    const state = generateStateFunction(requestObject)
    const scopeName = Array.isArray(scope) ? scope.join(' ') : scope;
    const hasResponseMode = scopeName.includes('email') || scopeName.includes('name');
    const urlOptions = Object.assign({}, callbackUriParams, {
      redirect_uri: callbackUri,
      scope: scope,
      state: state,
      ...(hasResponseMode && { response_mode: 'form_post' }),
    })
    const authorizationUri = oauth2.authorizationCode.authorizeURL(urlOptions)
    return authorizationUri
  }
```

![image](https://user-images.githubusercontent.com/9191544/137318341-eebdf650-342e-4cfc-ba57-322702501a45.png)

**Comment by climba03003** [comment]
> 
> 
> @climba03003 Hi! Thanks a lot for a quick reply! While your fix works, I still consider it a bug, because in my opinion the library has to add this additional query parameter itself, not the user of this library. Scope with `email` or `name` values is used in most cases for Apple Auth, so to prevent developers from using `callbackUriParams` each time they want to use Apple Auth and make your library more flexible and less error-prone, I'd recommend fixing it on a library level.

It is not a bug. But a dedicated behavior to Apple. 

You cannot tell if this breaks the others OAuth2.0 if you add the behavior you introduce.
https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes
`response_mode` should be OPTIONAL and it should be set by the user.
