### ISSUE TITLE
fastify.getAccessTokenFromAuthorizationCodeFlow is not a function

### ISSUE THREAD

**Issue by lagmanzaza** [fastify/fastify-oauth2#12]
I found a decorating in this plugin https://github.com/fastify/fastify-oauth2/blob/master/index.js#L96
but it doesn't work.

**Comment by lagmanzaza** [comment]
I could fix it

**Comment by contis2908** [comment]
How did you fix it ?

**Comment by lagmanzaza** [comment]
https://github.com/daniandl/fastify-oauth2/commit/79738c7fa40691da2a56c378744d24dca2e645b3

**Comment by Eomm** [comment]
@yarynakorduba would you mind opening a new issue with a reproducible case? (+ details like versions of module and node)

**Comment by yarynakorduba** [comment]
@Eomm sorry for disturbing, that was my mistake.
