### ISSUE TITLE
Is there any way to get header referer of request to startRedirectPath?

### ISSUE THREAD

**Issue by iamtmoe** [fastify/fastify-oauth2#121]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

 I need to redirect based on referer querystring after handle provider callback

**Comment by climba03003** [comment]
`startRedirectPath` need to be added before the server started. So, it should be a static fixed path.
Maybe something like `/login/:provider` is possible, you may investigate in it.

**Comment by iamtmoe** [comment]
@climba03003 Maybe I did't express clear, for example, if i set startRedirectPath to /login/github, and `/login?redirect_to=/` is my website login page，there is a button which request /login/github when clicked, after auth the user, I want to redirect to the / based on the querystring, i can get the initial request referer because the plugin handled the request and I don't know whether it expose the referer data.

**Comment by climba03003** [comment]
`generateStateFunction` can intercept the initial request, but you need to find a way to match the initial request and `callback` route.

**Comment by iamtmoe** [comment]
@climba03003 thx, it works, maybe this is exactly the usage scenario of state
