### ISSUE TITLE
date-fns/index.js not found

### ISSUE THREAD

**Issue by dmitrydrynov** [fastify/fastify-oauth2#131]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.1

### Plugin version

4.4.0

### Node.js version

16.13.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

`Cannot find module '...\node_modules\date-fns\index.js'. Please verify that the package.json has a valid "main" entry.`

I checked the installed files of the date-fns package and didn't see the index.js (or index.ts) file.

### Steps to Reproduce

npm install fasify-oauth2 (yarn add fasify-oauth2)
npm run dev (yarn dev)
got the error `Cannot find module '...\node_modules\date-fns\index.js'. Please verify that the package.json has a valid "main" entry.`

### Expected Behavior

don't have any errors

**Comment by mcollina** [comment]
I'm pretty sure there was a problem during your install, the `index.js` file is there for me
