### ISSUE TITLE
How to get a user's email / profile from a social network?

### ISSUE THREAD

**Issue by egoson** [fastify/fastify-oauth2#142]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I really can't find a place where I can get the user's email

**Comment by mbecker20** [comment]
It depends on the oauth provider. For Github, once you have a users access token from the oauth flow (and the scope array includes "user:email") you can make a get request to https://api.github.com/user/emails with authorization header set to `token ${accessToken}`. For Google, the access token that they send from the oauth flow is itself a jwt which can be decoded using fast-jwt. If the scope array scope includes "https://www.googleapis.com/auth/userinfo.email", then the payload of that jwt will include an "email" field. Those are the only two I had to figure out, but maybe it will give you an idea as to how to get any other ones you need -- look through the oauth provider docs.
