### ISSUE TITLE
How to set state?

### ISSUE THREAD

**Issue by daniandl** [fastify/fastify-oauth2#16]
I see the state gets generated automatically, without checking if one was passed..
Or am I missing something?

**Comment by allevo** [comment]
Hi!

Truly that feature should be implemented. There's a test for that case:
https://github.com/fastify/fastify-oauth2/blob/a5af052759fc9650036928332bd8cc010e7da5d3/test.js#L127

Anyway if you find an unexpected behaviour please repot it (with a piece of code) !

**Comment by daniandl** [comment]
I initially fixed this by passing the request (and reply) objects along to the custom `generateStateFunction()` you can pass in `options`.

This allowed me to intercept custom query parameters and decide on what the state should be/contain.
I dont know if this is the desired flow intended for fasitfy-oauth2, so I won't PR it.

I've now also switched away from this lib and use simple-oauth2 (which this is built on), as I needed a lot more configurability with the routes.
