### ISSUE TITLE
Property 'facebookOAuth2' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance, FastifyTypeProviderDefault>'.ts(2339)

### ISSUE THREAD

**Issue by gusparr28** [fastify/fastify-oauth2#166]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.1.0

### Plugin version

5.0.0

### Node.js version

16.10.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

I'm trying to use @fastify/oauth2 to implement Facebook Login and registering it like this:

```typescript
app.register(oauth2, {
  name: 'facebookOAuth2',
  credentials: {
    client: {
      id: FACEBOOK_ID!,
      secret: FACEBOOK_SECRET!,
    },
    auth: oauth2.FACEBOOK_CONFIGURATION,
  },
  startRedirectPath: '/login/facebook',
  callbackUri: 'http://localhost:3000/login/facebook/callback',
  scope: [],
});
```

then, when I try to use the plugin:

```typescript
app.get('/auth/signin/facebook', async (request: FastifyRequest, reply: FastifyReply) => {
  const token = await app.facebookOAuth2.getAccessTokenFromAuthorizationCodeFlow(request);

  console.log(token.access_token);

  return { access_token: token.access_token };
});
```

I'm getting this error:

```typescript
Property 'facebookOAuth2' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance, FastifyTypeProviderDefault>'.ts(2339)
```

### Steps to Reproduce

Just try to register @fastify/oauth2 and use it as I'm doing it

### Expected Behavior

I expect to be able to successfully use @fastify/oauth2

**Comment by climba03003** [comment]
Please read the `Usage with TypeScript` section.
https://github.com/fastify/fastify-oauth2#usage-with-typescript
