### ISSUE TITLE
support pass custom params to authorizationUri

### ISSUE THREAD

**Issue by meotimdihia** [fastify/fastify-oauth2#18]
![Code_2019-05-18_18-59-48](https://user-images.githubusercontent.com/300961/57969243-4e2f6280-799f-11e9-938d-7786640e7a25.png)

https://github.com/fastify/fastify-oauth2/blob/master/index.js#L59

We need params : access_type: offline to get refresh token with Google API

**Comment by Eomm** [comment]
Would you like to send a pr to add these kinds of customizations?

**Comment by meotimdihia** [comment]
Currently, I am not very good at javascript. But I just have tried to pull request: 
https://github.com/fastify/fastify-oauth2/pull/19

**Comment by meotimdihia** [comment]
https://github.com/fastify/fastify-oauth2/pull/19 
My commit was pulled. I close the issue.
