### ISSUE TITLE
simple-oauth2 seems unmaintained

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-oauth2#20]
If we look at https://github.com/lelylan/simple-oauth2/pulls, it seems that fixes/prs are waiting to be applied there.

Maybe we should think about a different dependency to use.

**Comment by kamikazechaser** [comment]
How about looking into grant? A discussion is ongoing asimov/grant#123

**Comment by Eomm** [comment]
It seems a really good idea! Also, [npm](https://www.npmjs.com/search?q=keywords:oauth2) agree: it is the first choice!

Reading the issue it seems they will build a plugin for this scope

**Comment by kamikazechaser** [comment]
However it seems it enforces the use of sessions. It may be useful in some scenarios but not all. Meanwhile I will check around if there is a similar library to `simple-oauth2`.

**Comment by mcollina** [comment]
We could just inherit simple-oauth2 or fork it.

Il giorno ven 14 giu 2019 alle 20:01 Mohammed Sohail <
notifications@github.com> ha scritto:

**Comment by jonathansamines** [comment]
Hi @mcollina I am the simple-oauth2's maintainer and have been working on resolving most of open issues. I would gladly work with the fastify community if there is still some remaining problem causing issues for this library.

*There is one problem though:* This plugin is currently using an old (and deprecated) version of simple-oauth2 (v1). I would love to get the library updated to v3, but note that it dropped support for Node 6 and older versions. If that is not an issue, just let me know and will gladly work on getting the library updated.

**Comment by mcollina** [comment]
Thanks for the help, it would be fantastic to get this updated.

**Comment by simov** [comment]
:wave: just wanted to let you know that I just released [Grant](https://github.com/simov/grant) v5.4.0 with a plugin for Fastify /cc @kamikazechaser

**Comment by fox1t** [comment]
@simov What do you think in making a wrapper (named `fastify-grant`) that exports just the fastify plugin and make a PR to https://www.fastify.io/ecosystem/ in order to be discovered more easily by the fastify users?

**Comment by simov** [comment]
Sure, I have a bunch of those already, prefixed grant-* like https://www.npmjs.com/package/grant-fastify, but we can have it the other way around, not a problem. As long as the users know where to look for docs/help, which is the grant repo, because I don't really have any of those grant-* packages as github repos, and instead all of them are pointing to the main repo.

The export is the lazily loaded one:

```js
module.exports = require('grant').fastify()
```

And in `package.json` I have:

```json
"dependencies": {
  "grant": "^5.4.0"
},
"peerDependencies": {
  "fastify": ">=3.0.0"
},
```

So at least it will warn if `fastify` is missing.

I can publish the package later today, and add it to the list :+1:

**Comment by simov** [comment]
PR here https://github.com/fastify/fastify/pull/2532 let me know if something is missing.
