### ISSUE TITLE
TWITCH_CONFIGURATION requires extra tokenRequestParams to be successful

### ISSUE THREAD

**Issue by whitep4nth3r** [fastify/fastify-oauth2#200]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Plugin version

7.0.1

### Node.js version

18.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.3.1 

### Description

In order to make a successful authentication call to Twitch, the plugin requires extra configuration that is not documented.

Here's an example of a successful authentication call, passing in extra `tokenRequestParams`:

Note:
The code below assumes that environment variables for the "Twitch Client ID" and "Twitch Secret" have been stored as secrets with the GitHub repository, and configured in `platformatic.service.json`

```js
  await app.register(fastifyOauth2, {
    name: "twitchOAuth2",
    scope: ["required:scopes"],
    credentials: {
      client: {
        id: opts.twitch_client_id,
        secret: opts.twitch_secret,
      },
      auth: fastifyOauth2.TWITCH_CONFIGURATION,
    },
    tokenRequestParams: {
      client_id: opts.twitch_client_id,
      client_secret: opts.twitch_secret,
    },
    startRedirectPath: "/twitch/login",
    callbackUri: "https://domain.tld/callback"
  });
```

### Steps to Reproduce

Attempt to authenticate without passing in `tokenRequestParams` and you'll make a `400 Bad Request` with the message `missing client id`.

### Expected Behavior

I would expect either the code example above to be documented, or for the plugin to automatically pass the client ID and secret through automatically, so the user only has to declare them once.

**Comment by mcollina** [comment]
Unfortunately, the current logic in this plugin does not allow to set those things automatically, as the configuration inside `auth` is just a preset. I'll document this.

**Comment by whitep4nth3r** [comment]
Thanks for the quick fix!
