### ISSUE TITLE
Not getting refresh_token in getAccessTokenFromAuthorizationCodeFlow

### ISSUE THREAD

**Issue by pavittar95** [fastify/fastify-oauth2#205]
### Prerequisites

- [ ] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

7.1.0

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.3.1 

### Description

I'm trying to implement a google login. Not sure if I need to pass anything else but I'm not getting refresh_token when calling 
getAccessTokenFromAuthorizationCodeFlow.

### Steps to Reproduce

I have followed the documentation.
https://github.com/fastify/fastify-oauth2

### Expected Behavior

```
import OauthPlugin, { Token } from "@fastify/oauth2";
import { FastifyInstance } from "fastify";

export const google = async (app: FastifyInstance) => {
  app.register(OauthPlugin, {
    name: "googleOAuth2",
    scope: ["profile", "email"],
    credentials: {
      client: {
        id: process.env.GOOGLE_CLIENT_ID || "",
        secret: process.env.GOOGLE_CLIENT_SECRET || "",
      },
      auth: OauthPlugin.GOOGLE_CONFIGURATION,
    },
    startRedirectPath: "/auth/google",
    callbackUri: process.env.GOOGLE_REDIRECT_URL || "",
    callbackUriParams: {
      // custom query param that will be passed to callbackUri
      prompt: "consent", // will tell Google to always ask for consent
    },
  });
  app.get("/auth/google/callback", async (request, reply) => {
    console.log("request----", request);
    const { token }: any =
      await app.googleOAuth2.getAccessTokenFromAuthorizationCodeFlow(request);
    console.log("token----", token);
/*token output {
    access_token: 'ya29.......',
    expires_in: 3599,
    scope: 'https://www.googleapis.com/auth/userinfo.email openid https://www.googleapis.com/auth/userinfo.profile',
    token_type: 'Bearer',
    id_token: 'eyJht........',
    expires_at: 2023-05-22T11:58:43.524Z
  }*/

    // console.log("newToken----", newToken);

    // if later you need to refresh the token you can use
    // const { token: newToken } = app.googleOAuth2.getNewAccessTokenUsingRefreshToken(token);

    reply.send({ access_token: token });
  });
};
```

**Comment by mcollina** [comment]
There is almost nothing specific to Google here, so I guess this is a bug upstream in `oauth2` module or possibly there is some other slight issue.

At this time I don't have time to debug this, however if you figure it out, would you mind adding a paragraph in the README to help others?

**Comment by climba03003** [comment]
`refresh_token` only given by Google when you first attempt to sign-in.
Please save it properly at the first time, otherwise it will not exist in the sub-sequential sign-in.

Consider signout the user with the given `access_token` or revoke the application from your account.
