### ISSUE TITLE
Scope:profile doesn't return email. Are there different scope parameters I can use?

### ISSUE THREAD

**Issue by contis2908** [fastify/fastify-oauth2#21]
I noticed that `scope: 'profile'` isn't returning the users email.
This might be a problem on my side but I was wondering if there are any other values for the scope parameter then profile. Although I would have expected that profile includes the email

**Comment by contis2908** [comment]
**Update**

I did some digging and found in [Google+ Authorizing API requests] the Email scope. 
This indeed returns the email and user image. However it of course misses all other values such as the username, firstname and so on.  (https://developers.google.com/+/web/api/rest/oauth)

As the value is in from of an array I would have figured that I can add multiple scope params but this isn't working for me. Not sure if this was intended the wau I abuse it.

Help would be appreciated.

**Comment by mcollina** [comment]
What would be the preferred fix for this?

**Comment by contis2908** [comment]
I am not totally familiar with the Authorizing API but I would assume that I can specify multiple scope paramters. 

`scope: ['https://www.googleapis.com/auth/plus.profile.emails.read', 'https://www.googleapis.com/auth/plus.login'],`

`scope: ['email', 'profile'],`

**Comment by yurakruhlyk** [comment]
@contis2908 I had the same problem, just use space instead of a comma, scope: ['email profile'].

**Comment by florianwiech** [comment]
> @contis2908 I had the same problem, just use space instead of a comma, scope: ['email profile'].

yep, found the same solution and works for me as well.
