### ISSUE TITLE
This plugin collides with fastify-cookie

### ISSUE THREAD

**Issue by agjs** [fastify/fastify-oauth2#213]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

@fastify/oauth2

### Node.js version

17.7.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

There is an issue with this plugin with used in conjunction with fastify-cookie.

* Register this plugin, e.g. fastify.register(...)
* Register fastify-cookie afterwards

Your server won't boot up due to an error: `fastify parseCookie decorator has already been added`

This happens because at the point when this plugin is loading, cookie [plugin indeed won't be registered](https://github.com/fastify/fastify-oauth2/blob/master/index.js#L65C2-L67C4). Whatsoever, since fastify-cookie itself isn't really checking if it was previously initialized (registered), it will try to do so and fail with the above error. 

### Steps to Reproduce

* Register this plugin, e.g. fastify.register(...)
* Register fastify-cookie afterwards

### Expected Behavior

Well, things should be working. What we've got was `fastify parseCookie decorator has already been added` instead.

We fixed it by simply changing the order of the plugins. Now, we register the fastify-cookie first, and then this plugin.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

---

Note that the behavior you are asking for is _tested_ in https://github.com/fastify/fastify-oauth2/blob/c1fb5aefb13b35f24beaf63ec8b75d1ba11e1bfe/test/index.test.js#L806-L853. So there is something else at play.

**Comment by agjs** [comment]
Hi @mcollina. Thanks for responding. I'll provide an example here tonight, and also happy to investigate this more and do a PR. I'll get back to you either tonight or tomorrow, as I'm at work now, so can't do much.

**Comment by Uzlopak** [comment]
maybe because you are not awaiting the register() calls. The test mentioned by @mcollina also dont await the register.

**Comment by agjs** [comment]
> maybe because you are not awaiting the register() calls. The test mentioned by @mcollina also dont await the register.

I actually tried with both, await and without it. The issue was solved by simply loading the cookie plugin first, then the oauth2.

**Comment by mcollina** [comment]
Ah yes of course. That's expected.
