### ISSUE TITLE
Open ID Connect Discovery support

### ISSUE THREAD

**Issue by big-kahuna-burger** [fastify/fastify-oauth2#241]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'm thinking about supporting [OpenID connect discovery](https://openid.net/specs/openid-connect-discovery-1_0.html) for this plugin.
`simple-oauth2` requires static host/path combinations to be configured as options, for someone that is using this library it might be annoying to configure everything. 

So idea is something like I've shown in [this comment](https://github.com/fastify/fastify-oauth2/pull/206#discussion_r1399712774). 
Essentially, send GET to discovery endpoint and then bake options based on the response that will fit into `credentials.auth` for the plugin.

Let me know what do you think how this API could look like based on example I'm giving below.

The only eventual drawback I see is that user needs to understand that GET request happens there, 
and that they have to now nest their `fastify.listen` call into continuation fn.

### Motivation

This plugin does best effort in providing some well known providers as well as options to support custom provider, but it still requires configuration of like 5 params. 
Often developers get it wrong, and it leads to invalid configs, false bug reports etc...

### Example

```js
const oauth2Plugin = require('fastify-oauth2')
const issuer = process.env.ISSUER

oauth2Plugin.discover(issuer)
  .then(metadata => {
    const pluginOpts = {
      credentials:  {
        auth: metadata,
        // ...other credential opts...
        client_id: ...
        client_secret: ...
      }
      // other opts
    }
    fastify.register(oauthPlugin, pluginOpts)
    fastify.listen({ port: 3000 })
  })
  .catch(err => {
    // handle discovery err
    
  })
```

**Comment by big-kahuna-burger** [comment]
Also, if #240 lands, then:
 Also something like this is possible.
 To show users and provide utility to extract from (eventual) `metadata.code_challenge_method` here by order of best effort, like S256 -> plain -> undefined. 
```js
const oauth2Plugin = require('fastify-oauth2')
const issuer = process.env.ISSUER

oauth2Plugin.discover(issuer)
  .then(metadata => {
    const pluginOpts = {
      credentials:  {
        auth: metadata,
        // ...other credential opts...
        client_id: ...
        client_secret: ...
      },
      pkce: oauthPlugin.selectPKCEMethod(metadata)
      // other opts
    }
    fastify.register(oauthPlugin, pluginOpts)
    fastify.listen({ port: 3000 })
  })
  .catch(err => {
    // handle discovery err
    
  })
```

**Comment by big-kahuna-burger** [comment]
Another option could be to just initially support actual metadata payload on filesystem and instruct users how to easily bake options using utility fn.
Like:
```sh
curl https://accounts.google.com/.well-known/openid-configuration > op.json
```
```js
const metadata = require('./op.json')
credentials.auth = { ...credentials.auth, ...oauth2Plugin.fromMetadataJSON(metadata) }
```

**Comment by mcollina** [comment]
Overall something that could be really nice is:

```js
    fastify.register(oauthPlugin, {
       discover: {
         issuer: process.env.ISSUER,
         onDiscover (metadata) {
            return {
              ...metadata,

            }
         }
       }
    })
```

**Comment by big-kahuna-burger** [comment]
Actually I settled on API that is much simpler:
```js
    fastify.register(oauthPlugin, {
      // ...other opts
       discover: {
         issuer: process.env.ISSUER
       }
    })
```

**Comment by big-kahuna-burger** [comment]
Actually I settled on API that is much simpler:
```js
    fastify.register(oauthPlugin, {
      // ...other opts
       discover: {
         issuer: process.env.ISSUER
       }
    })
```
