### ISSUE TITLE
Is it possible to create a local strategy?

### ISSUE THREAD

**Issue by Extarys** [fastify/fastify-oauth2#25]
Hi, thanks for creating this!

I looked at the simple-oauth2 package and I would like to use fastify-oauth2 with my own user database and not rely on X company.

I tried playing around a little but I couldn't make the plugin work without a provider or client's key.

Is there any plans to add this possibility in the future?

**Comment by mcollina** [comment]
We’ll be happy to get a PR to add support for this feature. In theory, there is nothing blocking this.

**Comment by Extarys** [comment]
@mcollina using the simple-oauth module it seems possible but the fastify plugin requires options that makes it impossible to not start it with 3rd party oauth configs.

Or did I miss something?

**Comment by mcollina** [comment]
Maybe. I'm not a direct user of this module, it would be good to have a repro script/or a PR that fixed this problem.

**Comment by Eomm** [comment]
Closing since it is doable now.

Here an example:

```
  fastify.register(oauth2, {
    name: 'discordOAuth2',
    credentials: {
      client: {
        id: fastify.config.DISCORD_CLIENT_ID,
        secret: fastify.config.DISCORD_SECRET
      },
      auth: {
        authorizeHost: 'https://discord.com',
        authorizePath: '/api/oauth2/authorize',
        tokenHost: 'https://discord.com',
        tokenPath: '/api/oauth2/token'
      }
    },
    // callbackUriParams: { permissions: fastify.config.DISCORD_PERMISSION }, // only for scope=bot
    scope: ['email', 'identify', 'gdm.join', 'connections'],
    // register a fastify url to start the redirect flow
    startRedirectPath: '/discord',
    // facebook redirect here after the user login
    callbackUri: `${fastify.config.BASE_URL}${opts.prefix || ''}/discord/callback`
  })
```
