### ISSUE TITLE
Misleading documentation for startRedirectPath

### ISSUE THREAD

**Issue by johnkmzhou** [fastify/fastify-oauth2#262]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In the README, under Usage, running the code will result in an error that states `Method 'GET' already declared for route '/login/facebook'`. The documentation should mention that the /login/facebook route only needs to be created if startRedirectPath has not been provided.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
