### ISSUE TITLE
TypeScript error for FastifyOauth2

### ISSUE THREAD

**Issue by johnkmzhou** [fastify/fastify-oauth2#264]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Node.js version

18

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Getting this TypeScript error:

> No overload matches this call.
>   Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyOAuth2Options, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
>     Argument of type 'FastifyOauth2' is not assignable to parameter of type 'FastifyPluginAsync<FastifyOAuth2Options, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>'.
>       Target signature provides too few arguments. Expected 3 or more, but got 2.

This looks to be similar to #120.

### Steps to reproduce

Run the following code with TypeScript (environment variables will need to be provided):

```
import Fastify from "fastify";
import oauthPlugin from "@fastify/oauth2";
import "dotenv/config";

const fastify = Fastify({
  logger: true,
});

// error will occur in register function
fastify.register(oauthPlugin, {
  name: 'custom',
  scope: ['openid'],
  credentials: {
    client: {
      id: process.env.CLIENT_ID,
      secret: process.env.CLIENT_SECRET,
    },
  },
  startRedirectPath: '/login',
  callbackUri: process.env.CALLBACK_URI,
  discovery: {
    issuer: process.env.DISCOVERY_ENDPOINT,
  },
});

fastify.get('/callback', async (req, reply) => {
  try {
    const { token } = await fastify.custom.getAccessTokenFromAuthorizationCodeFlow(req);

    reply.send(token);
  } catch (e) {
    fastify.log.error(e);
  }
});

try {
  await fastify.listen({ port: 3000 });
} catch (err) {
  fastify.log.error(err);
  process.exit(1);
}
```

_No response_

### Expected Behavior

No TypeScript error.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by mcc311** [comment]
Same problem here

**Comment by gotenxds** [comment]
Still a thing

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by daltojohnso** [comment]
Your environmental variables (process.env.CLIENT_ID etc) are likely typed as `string | undefined`. Make sure they are strings.

**Comment by aristofun** [comment]
Still a thing

**Comment by DanieleRusso97** [comment]
As far as I can see, this isn't an error.

Envs by default are `string | undefined` but some fields like `client.id`, `client.secret` and `discovery.issues` are required by fastify-oauth2.

So, you can provide defaults by doing something like:
`process.env.CLIENT_ID || ''`

Or better yet, you can handle cases where you forgot to set to set the envs before registering the plugin:

`if (!process.env.CLIENT_ID || ...) {
  throw new Error('Missing OAuth2 client credentials');
}`

**Comment by johnkmzhou** [comment]
You're right, it was an issue with undefined typing for environment variables. To be fair, the original TypeScript error gave little indication that was the problem. I will close this.
