### ISSUE TITLE
Support method to simplify token refresh

### ISSUE THREAD

**Issue by lmammino** [fastify/fastify-oauth2#27]
## 🚀 Feature Proposal

`simple-oauth2` supports a way to easily refresh access tokens by using the `refresh_token` (which you get if you request the `offline` scope:

```javascript
const AccessToken = require('simple-oauth2/lib/access-token')

async function refresh(tokenObject) {
  const token = new AccessToken(tokenObject);
  const refreshedToken = await token.refresh()

  return refreshedToken()
}

const token = {} // ... get token somehow
await refresh(token)
```

It would be cool to expose some shortcut in the fastify plugin to do this, given a OAuth2 token object

## Motivation

We already have a nice `this.getAccessTokenFromAuthorizationCodeFlow(request)` helper function. It would be nice to have something similar for renewing tokens as well.

What do you think?

I am happy to provide an implementation, if this idea makes sense for everyone.

## Example

(see above)

**Comment by Eomm** [comment]
Right now the refresh token is returned from the `getAccessTokenFromAuthorizationCodeFlow` but it is up to the user manage it right?

**Comment by allevo** [comment]
`getAccessTokenFromAuthorizationCodeFlow` returns `access token` and `refresh token` (not always). If your `access token` is expired, you can use `refresh token` for giving another `access token`.
You want to expose a utility for that, correct?

**Comment by lmammino** [comment]
Yes, something like `getAccessTokenFromRefreshToken` might make sense to keep consistent naming.

**Comment by allevo** [comment]
I'm super 👍 !

**Comment by lmammino** [comment]
Awesome, I'll try to assemble a PR during this weekend or next Monday :)

Thanks for the quick feedback!
