### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-oauth2#30]
Right now the readme doesn't show all the preset of this module:

- FACEBOOK_CONFIGURATION
- GITHUB_CONFIGURATION
- LINKEDIN_CONFIGURATION
- GOOGLE_CONFIGURATION
- MICROSOFT_CONFIGURATION

or how to use it with a custom configuration (using `credential.auth`)

It would be good to add it 👍

**Comment by RafaelGSS** [comment]
@Eomm I think it can be closed. Right?
