### ISSUE TITLE
How to judge whether the current token meets the requirements

### ISSUE THREAD

**Issue by a1047050321** [fastify/fastify-oauth2#31]
How to judge whether the current token meets the requirements，I dont know

**Comment by a1047050321** [comment]
scope:['profile'], has other option？

**Comment by Eomm** [comment]
Could you elaborate?
I don't understand the question

**Comment by a1047050321** [comment]
thx for replying. I want to do Google authorization, so scope: ['profile'], what is the meaning here, and what other options are there, for example, I want to do the validation of the company's domain name.

**Comment by Eomm** [comment]
You need to add you custom logic with the [`fastify-auth`](https://github.com/fastify/fastify-auth) plugin.

So the auth will be executed in order: before the oauth2 and then your logic
