### ISSUE TITLE
[Request] Twitter login support

### ISSUE THREAD

**Issue by blacksmoke26** [fastify/fastify-oauth2#37]
Can you please implement Twitter Auth?

**Comment by allevo** [comment]
Hi!
Thanks for checking out this project.
Would you mind sending a PR like [this](https://github.com/fastify/fastify-oauth2/pull/26/files)?

**Comment by blacksmoke26** [comment]
Yes, Will do.

Currently, I am on the implementation and testing phase. Once done. I will create a PR.

**Comment by kaatt** [comment]
@blacksmoke26 Can you post it here so we can review or create a PR based off it?

**Comment by kaatt** [comment]
@allevo The URLs for Twitter are defined here: https://github.com/jaredhanson/passport-twitter/blob/master/lib/strategy.js but I'm not sure which ones are required by this library.

**Comment by mcollina** [comment]
@kaatt if you'd like to send a fresh PR, that'd be handy. Also, adding support to `grant` for Fastify it would be nice.
