### ISSUE TITLE
Question: Some breaking changes allowed?

### ISSUE THREAD

**Issue by blacksmoke26** [fastify/fastify-oauth2#38]
Hello Devs,

I am tweaking module and making some breaking changes (_for me_). If these are welcoming, I will create a PR soon along with tests.

1. Add `request` third param in `checkStateFunction` and `generateStateFunction` _(+ promise support)_
2. New option `startRedirectCallback` + promise support_
3. Update all packages (some are deprecated, some are older)
4. Twitter API support
5. Update documentation according to the latest changes.

### Complete Example

```js
const oauthPlugin = require('fastify-oauth2');

const defaultState = require('crypto').randomBytes(10).toString('hex');

fastify.register(oauthPlugin, {
  name: 'facebookOAuth2',
  credentials: {
    client: {
    id: '<CLIENT_ID>',
    secret: '<CLIENT_SECRET>'
  },
    auth: oauthPlugin.FACEBOOK_CONFIGURATION,
  },
  generateStateFunction: async ( request ) => {
    // Perhaps request based state generation?
    return defaultState;
  },
  checkStateFunction: async ( state, request ) => {
    // Perhaps request based state validation?
    if ( state !== defaultState ) {
      throw new Error('Invalid state');
    }
  },
  startRedirectCallback: async ( request, reply ) => {
    const allowedIPs = [
      '127.0.0.1',
      // ...
    ];

    if ( !allowedIPs.includes(request.ip) ) {
      throw new Error('IP not allowed');
      // or
      // reply.code(403).send(new Error('IP not allowed'));
    }
  },
  startRedirectPath: '/login/facebook',
  callbackUri: `https://localhost:8000/login/facebook/callback`,
  //scope: 'email,public_profile',
});

fastify.get('/connect/facebook/callback', async function ( request, reply ) {
  try {
    const result = await this.facebookOAuth2.getAccessTokenFromAuthorizationCodeFlow(request);

    // Some complex logic here

    return result;
  } catch ( e ) {
    return e;
  }
});
```

If looks good. I will create a PR oi

**Comment by Eomm** [comment]
> If looks good. I will create a PR oi

Of course, it is!

> Add request third param in checkStateFunction and generateStateFunction (+ promise support)

this is a nice feature!

> Update all packages (some are deprecated, some are older)

I would keep this PR as last change

> some breaking changes

We will see if it is necessary 👍 but for now, it could be only for the change of the dependancies

Thanks 💪🏻
