### ISSUE TITLE
Incorrect default export for TypeScript

### ISSUE THREAD

**Issue by mfpopa** [fastify/fastify-oauth2#42]
## 🐛 Bug Report

The default export in [index.s.ts](https://github.com/fastify/fastify-oauth2/blob/master/index.d.ts) is incorrect.

It works with `require('fastify-oauth2')`, but it is buggy when used with `import * as fastifyOAuth2 from 'fastify-oauth2'` because the it forces us to do `fastifyOAuth2.default` which is undefined.

It should be `export = fastifyOauth2` like all other Fastify plugins so it works consistently for everyone, regardless if they use `require`, `import * as ...` or `import fastifyOauth2` with `esModuleInterop: true`.

## To Reproduce

```js
import * as fastifyOAuth2 from 'fastify-oauth2';

console.log(fastifyOAuth2.LINKEDIN_CONFIGURATION); // Property 'LINKEDIN_CONFIGURATION' does not exist on type 'typeof import("<my project path>/node_modules/fastify-oauth2/index")'.ts(2339)

console.log(fastifyOAuth2.default); // undefined
```

## Expected behavior

```js
import * as fastifyOAuth2 from 'fastify-oauth2';

console.log(fastifyOAuth2.LINKEDIN_CONFIGURATION); // See expected output below which works when using require().
// {
//   authorizeHost: 'https://www.linkedin.com',
//   authorizePath: '/oauth/v2/authorization',
//   tokenHost: 'https://www.linkedin.com',
//   tokenPath: '/oauth/v2/accessToken'
// }
```

## Your Environment

- *node version*: 12.16.3
- *fastify version*: 2.13.1
- *os*: Windows 10

## Fix

I am happy to submit a PR if necessary.

**Comment by allevo** [comment]
Hi!
thanks for reporting this bug. I'll happy to review PR!
