### ISSUE TITLE
Route level flexibility

### ISSUE THREAD

**Issue by kamikazechaser** [fastify/fastify-oauth2#45]
Right now the plugin assigns a static [GET route](https://github.com/fastify/fastify-oauth2/blob/master/index.js#L113) on boot up. This approach doesn't allow usage of request hooks or cleanly accessing the request object on the redirect path.

#38 is on the right track, but is still high level. I propose removing some enforcing logic inside the [`startRedirectHandler`](https://github.com/fastify/fastify-oauth2/blob/master/index.js#L57). Other functions could be created and exposed to the decorator that would allow one to get the authorization url. Those functions could be reused inside the `startRedirectHandler`. This would ensure there is no breaking change.

**Comment by mcollina** [comment]
Would you like to send a PR?
