### ISSUE TITLE
Check decorator existence

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify-oauth2#5]
If the decorator has already been declared `decorate` will throw an error here.
https://github.com/fastify/fastify-oauth2/blob/4c29d72b7b9dd8b2717ba039c6f1d65b9eac20df/index.js#L11

You can do two things:
- Use `hasDecorator` and in case `next(new Error(...))` ([docs](https://www.fastify.io/docs/latest/Decorators/#hasdecorator))
- Use a try catch block and call `next(err)`if it fails

**Comment by allevo** [comment]
> Use a try catch block and call next(err)if it fails

It is ok for me
