### ISSUE TITLE
v3.4.0 + LinkedIn broken?

### ISSUE THREAD

**Issue by mfpopa** [fastify/fastify-oauth2#60]
## 💥 Regression Report

I have a web application where I am using LinkedIn OAuth where I used version `3.3.0` of this plugin. All worked fine.

Once I have upgraded fastify from version `2.14.1` to `3.1.1` and this plugin to `3.4.0`, I started getting `Response Error: 400 Bad Request`. I have not tested other providers besides LinkedIn, so I don't know if this issue is specific to LinkedIn or not.

From the little debugging I did, I know for sure that the error is thrown from inside the plugin, not my code. If I downgrade back to `3.3.0` and keep fastify on `3.1.1`, everything works fine.

I don't have time at the moment, but I can setup a test repository and debug the issue later this month if it does not get resolved by then. For now I will keep my code base on `3.3.0`.

## Last working version

Worked up to version: `3.3.0`
Stopped working in version: `3.4.0`

## To Reproduce

1. Install `fastify@3.1.1`.
2. Install `fastify-oauth2@3.4.0`
3. Configure LinkedIn OAuth.

## Expected behavior

Everything works just like it did with `v3.3.0`

## Your Environment

- *node version*: `12`
- *fastify version*: `3.1.1`
- *os*: `Windows`

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Eomm** [comment]
@mcollina Looking the [release](https://github.com/fastify/fastify-oauth2/releases/tag/v3.3.1) it seems we released this plugin with fastify v3 as semver-patch: should not this version be a major one?
It should not be related to this issue but it could be for others.

@mfpopa are you using typescript?

**Comment by mcollina** [comment]
aaah it seems I have botched this. Will fix as soon as I can.

**Comment by mcollina** [comment]
I've released v3.5.0 which is essentially v3.3.0.
v4.0.0 targets Fastify v3.

**Comment by mfpopa** [comment]
@mcollina I can confirm that `3.5.0` works like `3.3.0`. I have only tested in fastify v3 though, so not sure about v2. I can also confirm that `4.0.0` is broken like `3.4.0`, but presumably that was the point of the bump to `4.0.0`.

I would like to look at this and provide a fix, but I very busy right now preparing for demos and new releases. In 1-2 weeks, I should have more time.

@Eomm I am using TypeScript, but I doubt this is a TypeScript issue because:

1. There is no type check error.
2. The issue occurs regardless if `esModuleInterop` is true or false, which could sometimes affect compilation if types are incorrect.
3. I traced the stack for a few function calls and ended up in `simple-oauth2 > authorization-code.js > getToken()` without getting any errors up to that point, so the error might be thrown inside one of the plugin's dependencies. I see that several dependencies have been bumped and some have been bumped more than 1 major version, so there could be some breaking changes in one of them.

**Comment by mfpopa** [comment]
I discovered that the issue was actually to do with a bug in my code. The token was being requested twice during the same HTTP request. The error was thrown in the code of the @hapi/wreck package. The first time the code was returning HTTP status 200, but the second time it was returning the 400 Bad Request error.
