### ISSUE TITLE
VKONTAKTE_CONFIGURATION has the same problem as LINKEDIN_CONFIGURATION, need add `options` params

### ISSUE THREAD

**Issue by ileonovdima** [fastify/fastify-oauth2#67]
VKONTAKTE_CONFIGURATION has the same problem as LINKEDIN_CONFIGURATION, need add `options` params 

    options: {
      bodyFormat: 'form',
      authorizationMethod: 'body'
    }

but if added `options`  displayed typescript error 

```
export interface Credentials {
  client: {
    id: string;
    secret: string;
  };
  auth: ProviderConfiguration;
}
```

`options` missing in index.d.ts

_Originally posted by @ileonovdima in https://github.com/fastify/fastify-oauth2/issues/58#issuecomment-688795058_

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
