### ISSUE TITLE
Always receiving Error: Invalid state even when using custom state functions.

### ISSUE THREAD

**Issue by himanshusaraswat** [fastify/fastify-oauth2#88]
## 🐛 Bug Report

Always receiving the ***Error: Invalid state*** while using a custom oauthPlugin as stated in sample.

## To Reproduce

I am trying to connect to Splitwise API.
1. Create a custom oauthPlugin as mentioned in the sample

```js
fastify.register(oauthPlugin, {
	name:  'customOauth2',
	credentials: {
	client: {
	id:  'key',
	secret:  'secret'
	},
	auth: {
	authorizeHost:  'https://secure.splitwise.com',
	authorizePath:  '/oauth/authorize',
	tokenHost:  'https://secure.splitwise.com',
	tokenPath:  '/oauth/token'
		}
			},

	startRedirectPath:  '/login',
	callbackUri:  'http://localhost:3000/login/callback'
});
```
2. Registered the route with fastify.
```js
fastify.get("/login/callback", async (request, reply) => {
try {
	console.log('PARAMETERS ARE',JSON.stringify(request.query));
	const  authorizationEndpoint = await  fastify.customOauth2.getAccessTokenFromAuthorizationCodeFlow(request)
	console.log(authorizationEndpoint);
	return { sucess:  false };
} catch (error) {
	console.error(error);
	return { sucess:  false };
}
});```

## Expected behavior

Should recieve the TOKEN as mentioned in sample
-   `access_token`
-   `refresh_token`  (optional, only if the  `offline scope`  was originally requested)
-   `token_type`  (generally  `'bearer'`)
-   `expires_in`  (number of seconds for the token to expire, e.g.  `240000`)
```
## Observations & head-banging so far :-(
I placed some console logs, in the library to find out, why is the state mismatched?
I observed, at the start of the server, a default state is set using:

    const  defaultState = require('crypto').randomBytes(10).toString('hex');
  
  The parameters received from the authorize UI is pretty decent as:

      PARAMETERS ARE {"code":"tfo8iycHkQUyVHnGeNYE","state":"fb09f28f167f8d9bfdd8"}
However, in the library's *"defaultCheckStateFunction"*, it does not consider/set the new state received & tries to match with the ***hex*** generated above.

    function  defaultCheckStateFunction (state, callback) {
	    console.log('INSIDE defaultCheckStateFunction',state,'defaultState::::::::', defaultState);
	    if (state === defaultState) {
	    console.log('INSIDE defaultCheckStateFunction',state,'defaultState::::::::', defaultState);
	    callback()
	    return
    }
	    console.log('ERROR****************************',state,'defaultState::::::::', defaultState);
	    callback(new  Error('Invalid state')) 
    }
Output is received as below which clearly states a mismatch:

    INSIDE defaultCheckStateFunction ***fb09f28f167f8d9bfdd8*** defaultState:::::::: ***89babc7653ca394b8528***
    ERROR**************************** ***fb09f28f167f8d9bfdd8*** defaultState:::::::: ***89babc7653ca394b8528***
    inside check STATE fb09f28f167f8d9bfdd8
    Error: Invalid state

I have also tried using the ***custom function to generate the state*** as mentioned in the  sample document, but it never executes the ***generateStateFunction***

This seems to be some kind of bug, any help is appreciated.
Thanks in advance.

Looking forward to her from you guys very soon.

## Your Environment

- *node version*: 14
- *fastify version*: >=3.14.1
- *os*: Windows,
- * "fastify-oauth2": "^4.2.1"*

**Comment by Eomm** [comment]
Duplicates https://github.com/fastify/help/issues/408
Closing
