### ISSUE TITLE
Is it possible to support multiple strategies?

### ISSUE THREAD

**Issue by vorillaz** [fastify/fastify-oauth2#9]
Hello there, great work with this decorator. My answer is pretty straightforward, is it possible to use more than one login strategies at once without registering the decorator multiple times?

**Comment by allevo** [comment]
Hi!
thanks for using `fastify-oauth2`.

The design of this module doesn't allow you to use multiple login strategies at once. But we are accepting PR! So, if you are interested, please send a PR and we will happy to discuss and merge it!

**Comment by bgbruno** [comment]
Hello - when I join that code I get

    Error: The decorator 'getAccessTokenFromAuthorizationCodeFlow' has already been added!

Q pls why is exist this issue? how fix it?

**Comment by bgbruno** [comment]
You can use ... hasdecorator API
thx @allevo - if I understand right I should create some condition
Q can you tell me how join that 2 routes with getAccessTokenFromAuthorizationCodeFlow together?

    fastify.get('/login/facebook/callback', function (request, reply) {
      this.getAccessTokenFromAuthorizationCodeFlow(request, (err, result) => {
        if (err) {
          reply.send(err)
          return
        }
    
        sget.concat({
          url: 'https://graph.facebook.com/v3.0/me',
          method: 'GET',
          headers: {
            Authorization: 'Bearer ' + result.access_token
          },
          json: true
        }, function (err, res, data) {
          if (err) {
            reply.send(err)
            return
          }
          reply.send(data)
        })
      })
    })

    fastify.get('/login/google/callback', function (request, reply) {
      this.getAccessTokenFromAuthorizationCodeFlow(request, (err, result) => {
        if (err) {
          reply.send(err)
          return
        }
    
        sget.concat({
          url: 'https://www.googleapis.com/plus/v1/people/me',
          method: 'GET',
          headers: {
            Authorization: 'Bearer ' + result.access_token
          },
          json: true
        }, function (err, res, data) {
          if (err) {
            reply.send(err)
            return
          }
          reply.send(data)
        })
      })
    })

we are accepting PR
Q btw what you mean by PR ?

**Comment by allevo** [comment]
Sorry for the delay:
Our code is not perfect. It fits our use case. But there's always a bug or new feature to implement!
So we are open and accept PR from other people

If you want to know more about PR: https://help.github.com/articles/about-pull-requests/

**Comment by ekuzu** [comment]
> You can use ... hasdecorator API
> thx @allevo - if I understand right I should create some condition
> Q can you tell me how join that 2 routes with getAccessTokenFromAuthorizationCodeFlow together?
> 
> ```
> fastify.get('/login/facebook/callback', function (request, reply) {
>   this.getAccessTokenFromAuthorizationCodeFlow(request, (err, result) => {
>     if (err) {
>       reply.send(err)
>       return
>     }
> 
>     sget.concat({
>       url: 'https://graph.facebook.com/v3.0/me',
>       method: 'GET',
>       headers: {
>         Authorization: 'Bearer ' + result.access_token
>       },
>       json: true
>     }, function (err, res, data) {
>       if (err) {
>         reply.send(err)
>         return
>       }
>       reply.send(data)
>     })
>   })
> })
> 
> fastify.get('/login/google/callback', function (request, reply) {
>   this.getAccessTokenFromAuthorizationCodeFlow(request, (err, result) => {
>     if (err) {
>       reply.send(err)
>       return
>     }
> 
>     sget.concat({
>       url: 'https://www.googleapis.com/plus/v1/people/me',
>       method: 'GET',
>       headers: {
>         Authorization: 'Bearer ' + result.access_token
>       },
>       json: true
>     }, function (err, res, data) {
>       if (err) {
>         reply.send(err)
>         return
>       }
>       reply.send(data)
>     })
>   })
> })
> ```
> we are accepting PR
> Q btw what you mean by PR ?

add `if(!fastify.hasDecorator('getAccessTokenFromAuthorizationCodeFlow'))` at line 95

**Comment by gjovanov** [comment]
Hey guys,
any progress on this one?

We are getting the same error if we try to configure 2 or more strategies:

`Error: The decorator 'getAccessTokenFromAuthorizationCodeFlow' has already been added!`

Any plans to finalize the pending PR?

Thanks.

**Comment by Eomm** [comment]
> Any plans to finalize the pending PR?

Would you like to complete the opened PR? It seems stale 😔

**Comment by vorillaz** [comment]
Just a quick update @Eomm @gjovanov. I have managed to recreate the oath strategy by myself as follows:

```javascript
// app.js
const auth = require('./auth.js');
const api = require('./api.js');
const fastify = require('fastify');

const server = fastify();

server.register(auth).register(api, {prefix: '/api'});
server.listen(3000, error => {
  console.log('Up and running')
});
```
```javascript
// auth.js
const fastifyPlugin = require('fastify-plugin');
const auth = require('./strategy');
const authorize = (fastify, opts = {}, next) => {
  async function verifyUser(request, reply, done) {
    if (userIsOk) {
      return done({ok: 'yes'})
    }
    return done(new Error('Missing token header'));
  }
  async function canEditResource(request, reply, done) {
    if (anotherStrategyFails) {
      return done({ok: 'yes'})
    }
    return done(new Error('Missing token header'));
  }

  fastify.register(auth);
  fastify.decorate('verifyUser', verifyUser);
  fastify.decorate('canEditProject', canEditResource);
  next(); 
}

module.exports = fastifyPlugin(authorize);
```

```javascript
//strategy.js
const fp = require('fastify-plugin');

const exec = (fn, req, rep) =>
  new Promise((resolve, reject) => {
    fn(req, rep, e => {
      if (e && e instanceof Error) {
        reject(e);
      } else {
        resolve();
      }
    });
  });

function auth(functions) {
  if (!Array.isArray(functions)) {
    throw new Error('You must give an array of functions to the auth function');
  }
  if (!functions.length) {
    throw new Error('Missing auth functions');
  }
  return (req, rep, done) => {
    const that = this;
    functions
      .reduce(
        (promiseChain, current) =>
          promiseChain.then(chainResults =>
            exec(current.bind(that), req, rep).then(currentResult => [
              ...chainResults,
              currentResult
            ])
          ),
        Promise.resolve([])
      )
      .then(() => {
        // All done.
        done();
      })
      .catch(e => {
        // Add code for the error
        rep.code(403);
        // and go on
        done(e);
      });
  };
}

const strategy = (fastify, opts, next) => {
  fastify.decorate('auth', auth);
  next();
};

module.exports = fp(strategy);

```

And finally, I can guard the API as follows:

```javascript
// api.js
module.exports = (fastify, opts = {}, next) => {
  const {verifyUser, canEditResource} = fastify;
  // User single strategy
  fastify.get('/user', {beforeHandler: fastify.auth([verifyUser])}, async (req, reply) => {
    const {user = null} = req;
    reply.send({...user});
  });

  // User single strategy
  fastify.get('/user', {beforeHandler: fastify.auth([verifyUser, canEditResource])}, async (req, reply) => {
    const {user = null} = req;
    reply.send({...user});
  })

  next();
}
```

**Comment by allevo** [comment]
#34 should fix this issue. Please reopen another if some errors occurred
